# Generated by Django 5.2.6 on 2026-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_remove_user_nome_remove_user_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('bartender', 'Bartender')], default='cliente', max_length=20),
        ),
    ]
