# Generated by Django 5.2.6 on 2026-03-23 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bartender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=3)),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('bartender', 'Bartender')], max_length=20)),
            ],
            options={
                'verbose_name': 'Termo de Uso',
                'verbose_name_plural': 'Termos de Uso',
            },
        ),
        migrations.CreateModel(
            name='AceiteTermos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.termos')),
            ],
            options={
                'verbose_name': 'Aceite de Termos',
                'verbose_name_plural': 'Aceites de Termos',
                'unique_together': {('termo', 'user')},
            },
        ),
    ]
