# Generated by Django 5.2.6 on 2026-04-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_mensagem_pedido_pagamento_chat_pedido_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='valor_hora',
        ),
    ]
