# Generated by Django 5.2.6 on 2026-04-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_proposta_valor_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='horas_aprovadas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proposta_aprovada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.proposta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_hora_aprovado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total_aprovado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
