# Generated by Django 5.2.6 on 2026-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido_horas_aprovadas_pedido_proposta_aprovada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartender',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bartender',
            name='stripe_onboarding_completo',
            field=models.BooleanField(default=False),
        ),
    ]
