# Generated by Django 5.2.6 on 2026-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bartender_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
