# Generated by Django 5.2.6 on 2026-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagamento_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='finalizado_pelo_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
