# Generated by Django 5.2.6 on 2026-04-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_evento_data'),
    ]

    operations = [
    ]
