# Generated by Django 5.2.6 on 2026-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_bartender_foto_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='especialidades',
            field=models.CharField(blank=True, choices=[('showman', 'Showman'), ('mixologista', 'Mixologista'), ('tradicional', 'Tradicional'), ('night_club', 'Night Club')], max_length=50),
        ),
    ]
