# Generated by Django 5.2.6 on 2026-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagamento_finalizado_pelo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto Bancário')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
