# Generated by Django 5.2.6 on 2026-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pagamento_stripe_payment_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('STRIPE', 'Stripe')], default='STRIPE', max_length=50),
        ),
    ]
