# Generated by Django 5.2.6 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pagamento_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
