# Generated by Django 5.2.6 on 2026-05-14 20:58

import django.db.models.deletion
import django.utils.timezone
import hashlib
from django.conf import settings
from django.db import migrations, models


TERMOS_CLIENTE = """Termos de Uso para Clientes - ProBar

1. A ProBar atua como plataforma de intermediação entre clientes e bartenders independentes.
2. O cliente é responsável por fornecer dados verdadeiros, manter sua conta segura e informar corretamente as características do evento.
3. O cliente deve garantir que o local do evento esteja apto, seguro e autorizado para a prestação do serviço contratado.
4. A contratação, negociação, pagamento, cancelamento e avaliação devem ocorrer pelos fluxos disponibilizados pela plataforma.
5. O cliente deve cumprir a legislação aplicável ao consumo de bebidas alcoólicas, inclusive impedindo fornecimento a menores de idade.
6. A ProBar pode suspender contas ou pedidos em caso de fraude, abuso, tentativa de contratação por fora da plataforma ou violação destes termos.
7. Valores, taxas, reembolsos e repasses seguem as regras exibidas na plataforma no momento da contratação.
8. A ProBar não substitui as responsabilidades diretas assumidas pelo cliente e pelo bartender na execução do evento.
9. Estes termos podem ser atualizados, e novas versões relevantes poderão exigir novo aceite.
"""

TERMOS_BARTENDER = """Termos de Uso para Bartenders - ProBar

1. A ProBar atua como plataforma de intermediação entre clientes e bartenders independentes, sem criação de vínculo empregatício.
2. O bartender é responsável por fornecer dados verdadeiros, manter seu perfil atualizado e executar os serviços aceitos com qualidade, pontualidade e segurança.
3. O bartender declara possuir experiência, capacidade e eventuais autorizações necessárias para prestar os serviços anunciados.
4. Propostas, negociações, pagamentos, cancelamentos e comunicações devem ocorrer pelos fluxos disponibilizados pela plataforma.
5. É proibido contornar a plataforma para fechar contratações originadas nela, salvo autorização expressa da ProBar.
6. O bartender deve cumprir a legislação aplicável ao consumo de bebidas alcoólicas, inclusive recusando atendimento irregular a menores de idade.
7. O bartender é responsável por suas obrigações fiscais, materiais, deslocamento e demais custos assumidos em cada contratação.
8. A ProBar pode suspender perfis em caso de fraude, má conduta, avaliações graves, no-show ou violação destes termos.
9. Estes termos podem ser atualizados, e novas versões relevantes poderão exigir novo aceite.
"""

POLITICA_PRIVACIDADE = """Política de Privacidade - ProBar

1. Esta política explica como a ProBar coleta, usa, armazena e compartilha dados pessoais para operar a plataforma.
2. Podemos tratar dados de cadastro, perfil, contato, fotos, eventos, endereços, mensagens, avaliações, dados técnicos e informações necessárias para pagamentos.
3. Dados de pagamento podem ser tratados por provedores especializados, como processadores de pagamento, conforme suas próprias regras de segurança e privacidade.
4. Os dados são usados para criar contas, viabilizar contratações, processar pagamentos, oferecer suporte, prevenir fraudes, cumprir obrigações legais e melhorar a plataforma.
5. Podemos compartilhar dados entre cliente e bartender quando necessário para a contratação e execução do serviço.
6. Também podemos compartilhar dados com fornecedores de hospedagem, pagamento, suporte, análise, segurança e autoridades quando houver obrigação legal.
7. A ProBar adota medidas razoáveis de segurança para proteger os dados pessoais contra acessos não autorizados, perdas e usos indevidos.
8. O titular pode solicitar acesso, correção, informação, exclusão quando aplicável, portabilidade e revogação de consentimentos opcionais.
9. Dúvidas e solicitações sobre privacidade podem ser enviadas pelo canal de atendimento informado pela ProBar.
10. Esta política pode ser atualizada, e novas versões relevantes poderão exigir nova ciência ou aceite.
"""


def criar_documentos_legais_iniciais(apps, schema_editor):
    DocumentoLegal = apps.get_model("core", "DocumentoLegal")

    documentos = [
        ("Termos de Uso para Clientes", TERMOS_CLIENTE, "termos_cliente"),
        ("Termos de Uso para Bartenders", TERMOS_BARTENDER, "termos_bartender"),
        ("Política de Privacidade", POLITICA_PRIVACIDADE, "politica_privacidade"),
    ]

    for titulo, conteudo, tipo in documentos:
        DocumentoLegal.objects.get_or_create(
            tipo=tipo,
            versao="1.0",
            defaults={
                "titulo": titulo,
                "conteudo": conteudo,
                "esta_ativo": True,
                "hash_conteudo": hashlib.sha256(conteudo.encode("utf-8")).hexdigest(),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_deletado', models.BooleanField(default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('versao', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('termos_cliente', 'Termos de Uso para Clientes'), ('termos_bartender', 'Termos de Uso para Bartenders'), ('politica_privacidade', 'Política de Privacidade')], max_length=30)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('vigente_a_partir_de', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash_conteudo', models.CharField(blank=True, editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'ordering': ['tipo', '-vigente_a_partir_de', '-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'versao'), name='unique_documento_legal_tipo_versao')],
            },
        ),
        migrations.CreateModel(
            name='AceiteDocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_deletado', models.BooleanField(default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('origem', models.CharField(default='cadastro', max_length=30)),
                ('hash_conteudo_aceito', models.CharField(editable=False, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_documentos_legais', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='core.documentolegal')),
            ],
            options={
                'verbose_name': 'Aceite de Documento Legal',
                'verbose_name_plural': 'Aceites de Documentos Legais',
                'ordering': ['-aceito_em'],
                'unique_together': {('documento', 'user')},
            },
        ),
        migrations.RunPython(criar_documentos_legais_iniciais, migrations.RunPython.noop),
    ]
