# Generated by Django 5.2.6 on 2026-05-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_documentolegal_aceitedocumentolegal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aceitetermos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aceitetermos',
            name='termo',
        ),
        migrations.RemoveField(
            model_name='aceitetermos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Termos',
        ),
        migrations.DeleteModel(
            name='AceiteTermos',
        ),
    ]
