# Generated by Codex on 2026-05-16

from django.db import migrations, models


def preencher_numero_bartender(apps, schema_editor):
    Pedido = apps.get_model('core', 'Pedido')
    db_alias = schema_editor.connection.alias

    bartender_ids = (
        Pedido.objects.using(db_alias)
        .order_by('bartender_id')
        .values_list('bartender_id', flat=True)
        .distinct()
    )

    for bartender_id in bartender_ids:
        pedidos = (
            Pedido.objects.using(db_alias)
            .filter(bartender_id=bartender_id)
            .order_by('criado_em', 'id')
        )
        for numero, pedido in enumerate(pedidos, start=1):
            pedido.numero_bartender = numero
            pedido.save(update_fields=['numero_bartender'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_aceitetermos_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_bartender',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(preencher_numero_bartender, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pedido',
            name='numero_bartender',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(
                fields=('bartender', 'numero_bartender'),
                name='unique_pedido_numero_por_bartender',
            ),
        ),
    ]
