# Generated by Codex on 2026-05-16

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def _to_decimal(value):
    if value is None:
        return Decimal('0')
    return Decimal(str(value))


def preencher_snapshots_propostas(apps, schema_editor):
    Proposta = apps.get_model('core', 'Proposta')
    db_alias = schema_editor.connection.alias

    propostas = (
        Proposta.objects.using(db_alias)
        .select_related('pedido__bartender')
        .order_by('id')
    )

    for proposta in propostas:
        pedido = proposta.pedido
        proposta_aprovada_id = getattr(pedido, 'proposta_aprovada_id', None)
        proposta_foi_aprovada = proposta_aprovada_id == proposta.id

        if proposta_foi_aprovada and pedido.valor_hora_aprovado is not None:
            valor_hora = _to_decimal(pedido.valor_hora_aprovado)
        else:
            valor_hora = _to_decimal(pedido.bartender.valor_hora)

        valor_total_calculado = (
            Decimal(proposta.horas or 0) * valor_hora
            + _to_decimal(proposta.valor_adicional)
            - _to_decimal(proposta.desconto)
        ).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

        if proposta_foi_aprovada and pedido.valor_total_aprovado is not None:
            valor_total = _to_decimal(pedido.valor_total_aprovado).quantize(
                Decimal('0.01'),
                rounding=ROUND_HALF_UP,
            )
        else:
            valor_total = valor_total_calculado

        proposta.valor_hora = valor_hora
        proposta.valor_total_snapshot = valor_total
        proposta.save(update_fields=['valor_hora', 'valor_total_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedido_numero_bartender'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_total_snapshot',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.RunPython(preencher_snapshots_propostas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proposta',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_total_snapshot',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
