# Generated by Codex on 2026-05-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_proposta_financial_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='presenca_status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('PRESENTE', 'Presente'),
                    ('AUSENTE', 'Ausente'),
                ],
                default='PENDENTE',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='pedido',
            name='presenca_origem',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CLIENTE', 'Cliente'),
                    ('AUTOMATICA', 'Automatica'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='pedido',
            name='presenca_registrada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='presenca_registrada_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='presencas_registradas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='pedido',
            name='presenca_observacao',
            field=models.TextField(blank=True),
        ),
    ]
