# Generated by Django 5.2.6 on 2026-05-17 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedido_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_deletado', models.BooleanField(default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CANCELAMENTO_AUTORIZACAO', 'Cancelamento de autorizacao'), ('REEMBOLSO_CAPTURADO', 'Reembolso de pagamento capturado'), ('SEM_COBRANCA', 'Sem cobranca')], default='CANCELAMENTO_AUTORIZACAO', max_length=40)),
                ('motivo', models.CharField(choices=[('AUSENCIA_BARTENDER', 'Ausencia do bartender')], default='AUSENCIA_BARTENDER', max_length=40)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONTESTADA', 'Contestada'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada'), ('CONCLUIDA', 'Concluida'), ('FALHOU', 'Falhou')], default='ABERTA', max_length=20)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moeda', models.CharField(default='brl', max_length=3)),
                ('observacao_cliente', models.TextField(blank=True)),
                ('resposta_bartender', models.TextField(blank=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('decisao_admin', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_reembolso', to='core.bartender')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_reembolso', to='core.cliente')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisoes_reembolso', to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_reembolso', to='core.pagamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_reembolso', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Solicitacao de reembolso',
                'verbose_name_plural': 'Solicitacoes de reembolso',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ABERTA', 'CONTESTADA', 'APROVADA', 'FALHOU'])), fields=('pedido',), name='unique_solicitacao_reembolso_ativa_por_pedido')],
            },
        ),
    ]
