# Generated by Django 5.2.6 on 2026-05-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_solicitacaoreembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='execucao_financeira_concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='execucao_financeira_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='stripe_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='stripe_idempotency_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
