[pytest]
DJANGO_SETTINGS_MODULE = probar_api.settings
python_files = test.py tests.py test_*.py tests_*.py *_test.py *_tests.py
addopts = 
    --doctest-modules
    --strict-markers
markers = 
    slow: Run tests that are slow
    fast: Run fast tests
    postgres: Tests that require a Postgres database (use Testcontainers or local Docker)